version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pre-commit
    versions:
    - 2.10.0
    - 2.10.1
    - 2.11.0
    - 2.11.1
    - 2.12.0
  - dependency-name: docutils
    versions:
    - "0.16"
    - "0.17"
  - dependency-name: numpy
    versions:
    - 1.19.5
    - 1.20.0
    - 1.20.1
    - 1.20.2
  - dependency-name: openpyxl
    versions:
    - 3.0.6
    - 3.0.7
  - dependency-name: pandas
    versions:
    - 1.2.1
    - 1.2.2
    - 1.2.3
  - dependency-name: sentry-sdk
    versions:
    - 0.19.5
    - 0.20.0
    - 0.20.1
    - 0.20.2
    - 0.20.3
  - dependency-name: soupsieve
    versions:
    - "2.1"
    - "2.2"
  - dependency-name: pytz
    versions:
    - "2020.5"
  - dependency-name: django
    versions:
    - 2.2.13
  - dependency-name: nltk
    versions:
    - 3.4.5
