# Generated by Django 2.2 on 2019-05-13 18:10

# from django.db import migrations


# def update_body(apps, schema_editor):
#     Post = apps.get_model('posts', 'Post')

#     for instance in Post.objects.all():
#         instance.body = instance.content
#         instance.save()

# class Migration(migrations.Migration):

#     dependencies = [
#         ('posts', '0006_auto_20190513_1810'),
#     ]

#     operations = [
#         migrations.RunPython(
#             update_body, reverse_code=migrations.RunPython.noop),
#     ]


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190513_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='Post',
            name='_body_excerpt',
            field=models.TextField(null=True),  # unique=True
            preserve_default=False,
        ),
    ]

