# Generated by Django 2.2 on 2019-05-11 16:43

from django.db import migrations, models
# from django.utils.text import slugify

# def migrate_data_forward(apps, schema_editor):
#     try:
#         Post = apps.get_model('posts', 'Post')
#         for instance in Post.objects.all():
#             print("Generating slug for %s" % instance)
#             instance.save()  # Will trigger slug update
#     except LookupError:
#         # The old app isn't installed.
#         pass


# def update_slugs(apps, schema_editor):
#     Post = apps.get_model('posts', 'Post')

#     for instance in Post.objects.all():
#         instance.slug = slugify(instance.title)
#         instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190414_1924'),
    ]

    operations = [

        migrations.AddField(
            model_name='Post',
            name='slug',
            field=models.SlugField(null=True),  # unique=True
            preserve_default=False,
        ),

    ]
