# Generated by Django 2.2 on 2019-05-11 19:10

from django.db import migrations
from django.utils.text import slugify


def update_slugs(apps, schema_editor):
    Post = apps.get_model('posts', 'Post')

    for instance in Post.objects.all():
        instance.slug = slugify(instance.title[:49])
        instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190511_1643'),
    ]

    operations = [
        migrations.RunPython(
            update_slugs, reverse_code=migrations.RunPython.noop),
    ]
