# Generated by Django 2.2 on 2019-05-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='alt',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
