# Generated by Django 2.2.3 on 2019-11-17 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_postimage_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='big',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ipython',
        ),
        migrations.RemoveField(
            model_name='post',
            name='percent_read',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_views',
        ),
    ]
